set path=%path%;"C:\Program Files (x86)\WinZip"
set uddeim=uddeIM_4.0

md %uddeIM%_unzip1st
xcopy /e "..\uddeIM\trunk\3rd party"						"%uddeIM%_unzip1st\3rd party\"
xcopy /e "..\uddeIM\trunk\DEVELOPER"						"%uddeIM%_unzip1st\DEVELOPER\"
xcopy /e "..\uddeIM\trunk\EXTRAS"							"%uddeIM%_unzip1st\EXTRAS\"
xcopy /e "..\uddeIM\trunk\LANGUAGES"						"%uddeIM%_unzip1st\LANGUAGES\"
xcopy /e "..\uddeIM\trunk\LICENSES"							"%uddeIM%_unzip1st\LICENSES\"
xcopy /e "..\uddeIM\trunk\README"							"%uddeIM%_unzip1st\README\"
xcopy /e "..\uddeIM\trunk\cb2_plug_pms_uddeim"				"%uddeIM%_unzip1st\cb2_plug_pms_uddeim\"
xcopy /e "..\uddeIM\trunk\cb2_plug_pms_uddeim_blocking"		"%uddeIM%_unzip1st\cb2_plug_pms_uddeim_blocking\"
xcopy /e "..\uddeIM\trunk\cb2_plug_pms_uddeim_inbox"		"%uddeIM%_unzip1st\cb2_plug_pms_uddeim_inbox\"
xcopy /e "..\uddeIM\trunk\cb2_plug_pms_uddeim_profilelink"	"%uddeIM%_unzip1st\cb2_plug_pms_uddeim_profilelink\"
xcopy /e "..\uddeIM\trunk\cb_plug_pms_uddeim"				"%uddeIM%_unzip1st\cb_plug_pms_uddeim\"
xcopy /e "..\uddeIM\trunk\cb_plug_pms_uddeim_blocking"		"%uddeIM%_unzip1st\cb_plug_pms_uddeim_blocking\"
xcopy /e "..\uddeIM\trunk\cb_plug_pms_uddeim_inbox"			"%uddeIM%_unzip1st\cb_plug_pms_uddeim_inbox\"
xcopy /e "..\uddeIM\trunk\cb_plug_pms_uddeim_profilelink"	"%uddeIM%_unzip1st\cb_plug_pms_uddeim_profilelink\"
xcopy /e "..\uddeIM\trunk\com_uddeim"						"%uddeIM%_unzip1st\com_uddeim\"
xcopy /e "..\uddeIM\trunk\mod_uddeim"						"%uddeIM%_unzip1st\mod_uddeim\"
xcopy /e "..\uddeIM\trunk\mod_uddeim_mailbox"				"%uddeIM%_unzip1st\mod_uddeim_mailbox\"
xcopy /e "..\uddeIM\trunk\mod_uddeim_statistics"			"%uddeIM%_unzip1st\mod_uddeim_statistics\"
xcopy /e "..\uddeIM\trunk\plug_uddeim_contentlink"			"%uddeIM%_unzip1st\plug_uddeim_contentlink\"
xcopy /e "..\uddeIM\trunk\plug_uddeim_searchbot"			"%uddeIM%_unzip1st\plug_uddeim_searchbot\"
copy     "..\uddeIM\trunk\*.txt"							"%uddeIM%_unzip1st\"
del "%uddeIM%_unzip1st\com_uddeim\language.utf8\doall.bat"
del "%uddeIM%_unzip1st\com_uddeim\language.utf8\iconv.exe"
del "%uddeIM%_unzip1st\com_uddeim\language.utf8\libcharset1.dll"
del "%uddeIM%_unzip1st\com_uddeim\language.utf8\libiconv.htm"
del "%uddeIM%_unzip1st\com_uddeim\language.utf8\libiconv2.dll"
del "%uddeIM%_unzip1st\com_uddeim\language.utf8\libintl3.dll"
del "%uddeIM%_unzip1st\com_uddeim\language.utf8\doall_cleanup.bat"

md %uddeIM%_j16_unzip1st
xcopy /e "..\uddeIM\trunk\3rd party"						"%uddeIM%_j16_unzip1st\3rd party\"
xcopy /e "..\uddeIM\trunk\DEVELOPER"						"%uddeIM%_j16_unzip1st\DEVELOPER\"
xcopy /e "..\uddeIM\trunk\EXTRAS"							"%uddeIM%_j16_unzip1st\EXTRAS\"
xcopy /e "..\uddeIM\trunk\LANGUAGES"						"%uddeIM%_j16_unzip1st\LANGUAGES\"
xcopy /e "..\uddeIM\trunk\LICENSES"							"%uddeIM%_j16_unzip1st\LICENSES\"
xcopy /e "..\uddeIM\trunk\README"							"%uddeIM%_j16_unzip1st\README\"
xcopy /e "..\uddeIM\trunk\cb2_plug_pms_uddeim"				"%uddeIM%_j16_unzip1st\cb2_plug_pms_uddeim\"
xcopy /e "..\uddeIM\trunk\cb2_plug_pms_uddeim_blocking"		"%uddeIM%_j16_unzip1st\cb2_plug_pms_uddeim_blocking\"
xcopy /e "..\uddeIM\trunk\cb2_plug_pms_uddeim_inbox"		"%uddeIM%_j16_unzip1st\cb2_plug_pms_uddeim_inbox\"
xcopy /e "..\uddeIM\trunk\cb2_plug_pms_uddeim_profilelink"	"%uddeIM%_j16_unzip1st\cb2_plug_pms_uddeim_profilelink\"
xcopy /e "..\uddeIM\trunk\cb_plug_pms_uddeim"				"%uddeIM%_j16_unzip1st\cb_plug_pms_uddeim\"
xcopy /e "..\uddeIM\trunk\cb_plug_pms_uddeim_blocking"		"%uddeIM%_j16_unzip1st\cb_plug_pms_uddeim_blocking\"
xcopy /e "..\uddeIM\trunk\cb_plug_pms_uddeim_inbox"			"%uddeIM%_j16_unzip1st\cb_plug_pms_uddeim_inbox\"
xcopy /e "..\uddeIM\trunk\cb_plug_pms_uddeim_profilelink"	"%uddeIM%_j16_unzip1st\cb_plug_pms_uddeim_profilelink\"
xcopy /e "..\uddeIM\trunk\com_uddeim_j16"					"%uddeIM%_j16_unzip1st\com_uddeim_j16\"
xcopy /e "..\uddeIM\trunk\com_uddeim_j16_english_only"		"%uddeIM%_j16_unzip1st\com_uddeim_j16_english_only\"
xcopy /e "..\uddeIM\trunk\mod_uddeim_j16"					"%uddeIM%_j16_unzip1st\mod_uddeim_j16\"
xcopy /e "..\uddeIM\trunk\mod_uddeim_mailbox_j16"			"%uddeIM%_j16_unzip1st\mod_uddeim_mailbox_j16\"
xcopy /e "..\uddeIM\trunk\mod_uddeim_statistics_j16"		"%uddeIM%_j16_unzip1st\mod_uddeim_statistics_j16\"
xcopy /e "..\uddeIM\trunk\plug_uddeim_contentlink_j16"		"%uddeIM%_j16_unzip1st\plug_uddeim_contentlink_j16\"
xcopy /e "..\uddeIM\trunk\plug_uddeim_searchbot_j16"		"%uddeIM%_j16_unzip1st\plug_uddeim_searchbot_j16\"
copy     "..\uddeIM\trunk\*.txt"							"%uddeIM%_j16_unzip1st\"							

md %uddeIM%_j30_unzip1st
xcopy /e "..\uddeIM\trunk\3rd party"						"%uddeIM%_j30_unzip1st\3rd party\"
xcopy /e "..\uddeIM\trunk\DEVELOPER"						"%uddeIM%_j30_unzip1st\DEVELOPER\"
xcopy /e "..\uddeIM\trunk\EXTRAS"							"%uddeIM%_j30_unzip1st\EXTRAS\"
xcopy /e "..\uddeIM\trunk\LANGUAGES"						"%uddeIM%_j30_unzip1st\LANGUAGES\"
xcopy /e "..\uddeIM\trunk\LICENSES"							"%uddeIM%_j30_unzip1st\LICENSES\"
xcopy /e "..\uddeIM\trunk\README"							"%uddeIM%_j30_unzip1st\README\"
xcopy /e "..\uddeIM\trunk\cb2_plug_pms_uddeim"				"%uddeIM%_j30_unzip1st\cb2_plug_pms_uddeim\"
xcopy /e "..\uddeIM\trunk\cb2_plug_pms_uddeim_blocking"		"%uddeIM%_j30_unzip1st\cb2_plug_pms_uddeim_blocking\"
xcopy /e "..\uddeIM\trunk\cb2_plug_pms_uddeim_inbox"		"%uddeIM%_j30_unzip1st\cb2_plug_pms_uddeim_inbox\"
xcopy /e "..\uddeIM\trunk\cb2_plug_pms_uddeim_profilelink"	"%uddeIM%_j30_unzip1st\cb2_plug_pms_uddeim_profilelink\"
xcopy /e "..\uddeIM\trunk\cb_plug_pms_uddeim"				"%uddeIM%_j30_unzip1st\cb_plug_pms_uddeim\"
xcopy /e "..\uddeIM\trunk\cb_plug_pms_uddeim_blocking"		"%uddeIM%_j30_unzip1st\cb_plug_pms_uddeim_blocking\"
xcopy /e "..\uddeIM\trunk\cb_plug_pms_uddeim_inbox"			"%uddeIM%_j30_unzip1st\cb_plug_pms_uddeim_inbox\"
xcopy /e "..\uddeIM\trunk\cb_plug_pms_uddeim_profilelink"	"%uddeIM%_j30_unzip1st\cb_plug_pms_uddeim_profilelink\"
xcopy /e "..\uddeIM\trunk\com_uddeim_j30"					"%uddeIM%_j30_unzip1st\com_uddeim_j30\"
xcopy /e "..\uddeIM\trunk\mod_uddeim_j30"					"%uddeIM%_j30_unzip1st\mod_uddeim_j30\"
xcopy /e "..\uddeIM\trunk\mod_uddeim_mailbox_j30"			"%uddeIM%_j30_unzip1st\mod_uddeim_mailbox_j30\"
xcopy /e "..\uddeIM\trunk\mod_uddeim_statistics_j30"		"%uddeIM%_j30_unzip1st\mod_uddeim_statistics_j30\"
xcopy /e "..\uddeIM\trunk\plug_uddeim_contentlink_j30"		"%uddeIM%_j30_unzip1st\plug_uddeim_contentlink_j30\"
xcopy /e "..\uddeIM\trunk\plug_uddeim_hooks_j30"			"%uddeIM%_j30_unzip1st\plug_uddeim_hooks_j30\"
xcopy /e "..\uddeIM\trunk\plug_uddeim_searchbot_j30"		"%uddeIM%_j30_unzip1st\plug_uddeim_searchbot_j30\"
copy     "..\uddeIM\trunk\*.txt"							"%uddeIM%_j30_unzip1st\"							

pause
